//  Problem 1
/*
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
Find the sum of all the multiples of 3 or 5 below 1000.
*/
function sumOfMultiples() {
  let sum = 0;
  for (let i = 1; i < 1000; i++) {
    if (i % 3 === 0 || i % 5 === 0) {
      sum += i;
    }
  }
  console.log(sum);
}

/////////////////////
// Problem 2
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
Generate the Fibonacci sequence up to 1000 values
*/
function generateFibonacci() {
  let fibonacciArray = [1, 2];
  for (let i = 1; i < 999; i++) {
    let newValue = fibonacciArray[fibonacciArray.length - 1] + fibonacciArray[fibonacciArray.length - 2];
    fibonacciArray.push(newValue);
  }
  console.log(fibonacciArray);
}